bno055_driver_node:
  ros__parameters:
    debug: True
    device: "/dev/i2c-7"
    address: 0x28
    rate: 100
    accel_offset:
      x: -50
      y: -60
      z: -36
      r: 1000
    gyro_offset:
      x: 0
      y: 0
      z: 1
    mag_offset:
      x: 176
      y: 211
      z: 1
      r: 1946